# Generated by Django 5.0.3 on 2024-03-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_category', models.CharField(max_length=20)),
                ('product_price', models.IntegerField()),
                ('product_manufacturing_date', models.DateField()),
                ('product_expiry_date', models.DateField()),
                ('product_HSN_no', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
            ],
        ),
    ]
